AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Parameters:
  DeploymentBucketName:
    Type: String
  DeploymentBucketKey:
    Type: String
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !Ref DeploymentBucketName
        Key: !Ref DeploymentBucketKey
    Events:
      GetResource:
        RestApiId: !Ref MyApi
        Type: Api
        Properties:
          Path: /
          Method: get
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Stage
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "TestAPI"
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
                responses: {}
                httpMethod: "GET"
                type: "aws"
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/test/"