AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Parameters:
  DeploymentBucketName:
    Type: String
  DeploymentBucketKey:
    Type: String
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !Ref DeploymentBucketName
        Key: !Ref DeploymentBucketKey
    Events:
      GET:
        Type: Api
        Properties:
          Path: /
          Method: get

Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resource/"